version: '2'

services:
  demo:
    build:
      context: .
      dockerfile: Dockerfile1
    environment:
      - BUILD_ON_DOCKER=True
    image: demo:latest
    ports:
      - "5000:5000"
    volumes:
      - .:/demo
    working_dir: /demo
    command: ./wipe-kraken.sh

