apiVersion: v1
kind: Service
metadata:
  name: hugo-canary
  labels:
    app: hugo-canary
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: hugo-canary
