apiVersion: v1
kind: Service
metadata:
  name: hugo-blue-green
  labels:
    app: hugo-blue-green
spec:
  type: LoadBalancer
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: hugo-blue-green
    color: blue
